language: rust
os:
  - linux
  - osx
  - windows
rust:
  - 1.34.2
  - stable
  - nightly
matrix:
  include:
    - rust: stable
      env: FLAGS="--no-default-features"
    - rust: nightly
      env: FLAGS="-Z minimal-versions"
    - rust: stable
      env:
        - FLAGS="--all-features"
        - IMAGE_PNG_TEST=yes
    - rust: nightly
      env:
        - FUZZIT_TARGET="png-decoder"
        - FUZZIT_BINARY="decode"
      services:
        - docker
  allow_failures:
    - rust: nightly
      env: FLAGS="-Z minimal-versions"

before_install:
    - rustup component add rustfmt
    - cargo fmt --version

script:
  - cargo fmt --all -- --check
  - cargo build -v $FLAGS
  - cargo doc -v $FLAGS
  - if [ -n "$IMAGE_PNG_TEST" ]; then cargo test -v $FLAGS; fi
  - if [ -n "$FUZZIT_TARGET" ]; then ./fuzzit.sh "$FUZZIT_TARGET" "$FUZZIT_BINARY"; fi
